name: <+pipeline.name>
replicas: 1

image1: <+artifact.image>
dockercfg1: <+artifact.imagePullSecret>

image2: <+artifacts.sidecars.sidecar1.image>
dockercfg2: <+artifacts.sidecars.sidecar1.imagePullSecret>


createNamespace: true
namespace: <+infra.namespace>

env:
  config:
    key1: value1
  secrets:
    key2: value2
